version: '3.8'
services:
  nginx:
    image: nginx:1.18.0
    container_name: lqy-nginx
    ports:
      - 80:80
    volumes:
      - /www:/var/www/html/:rw
      - /home/docker/lnmp/nginx/conf/conf.d:/etc/nginx/conf.d/:rw
      - /home/docker/lnmp/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/docker/lnmp/nginx/log:/var/log/nginx/:rw
    restart: always
  php:
    image: php:lqy-php74
    container_name: lqy-php74
    volumes:
      - /www:/var/www/html/:rw
      - /home/docker/lnmp/php/7.4.8/php.ini:/usr/local/etc/php/php.ini:ro
      - /home/docker/lnmp/php/7.4.8/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
  mysql:
    container_name: lqy-mysql
    image: mysql:8.0.21
    ports:
      - 3306:3306
    volumes:
      - /home/docker/lnmp/mysql/data:/var/lib/mysql
      - /home/docker/lnmp/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 543492227@qq.com
    command:
      --default-authentication-plugin=mysql_native_password
      --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
  redis:
    container_name: lqy-redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    volumes:
      - /home/docker/lnmp/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/docker/lnmp/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    sysctls:
      net.core.somaxconn: 65535
    restart: unless-stopped

networks:
  default:
    external:
      name: lqy-network

