version: '3.8'
services:
  nginx:
    image: ${NGINX_VERSION}
    container_name: lqy-nginx
    ports:
      - ${HTTP_HOST}:80
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php:
    image: ${PHP_VERSION}
    container_name: lqy-php74
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
  mysql:
    container_name: lqy-mysql
    image: ${MYSQL_VERSION}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
  redis:
    container_name: lqy-redis
    image: ${REDIS_VERSION}
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    sysctls:
      net.core.somaxconn: 65535
    restart: unless-stopped

networks:
  default:
    external:
      name: lqy-network
